local GameConfig = {
	DECK_SIZE = 20,
	MAX_COPIES_PER_CARD = 1,
	LOCATIONS_PER_GAME = 2,
	SLOTS_PER_LOCATION = 3,
	GRID_COLUMNS = 3,
	GRID_ROWS = 1,
	STARTING_HAND_SIZE = 3,
	STARTING_MAX_ENERGY = 0,
	ENERGY_PER_TURN = 1,
	CARDS_DRAWN_PER_TURN = 1,
	MAX_HAND_SIZE = 7,
	TURN_TIMER_SECONDS = 30,
	POINTS_TO_WIN = 20,

	-- Starter deck (20 cards, used for new players and the bot)
	STARTER_DECK = {
		"SPARK", "SCOUT", "EMBER", "SEEDLING",
		"IRON_GUARD", "FROST_SPRITE", "LOOKOUT", "FLAME_IMP",
		"STONE_GOLEM", "HEALER", "SABOTEUR",
		"WAR_BEAST", "COMMANDER", "BERSERKER", "SHIELD_WALL",
		"DRAGON", "STORM_MAGE", "HIGH_PRIESTESS",
		"TITAN", "OVERLORD",
	},
}

return GameConfig
